@NAMED-QUERY(name="SELECT-CRAWL-LIMIT-URLS", 
    sql="SELECT C.ID, C.STATUS, U.URL, C.URL_BASE
    FROM CRAWL C 
    INNER JOIN CRAWL_URL U ON U.CRAWL_ID = C.ID 
    WHERE C.ID = ? ORDER BY U.CRAWL_ID"
);

@NAMED-QUERY(name="INSERT-CRAWL", 
    sql="INSERT INTO CRAWL (ID, STATUS, URL_BASE) VALUES (?, ?, ?)"
);

@NAMED-QUERY(name="INSERT-CRAWL-URL", 
    sql="INSERT INTO CRAWL_URL (URL, CRAWL_ID) VALUES (?, ?)"
);

@NAMED-QUERY(name="UPDATE-CRAWL-STATUS", 
    sql="UPDATE CRAWL SET STATUS = ? WHERE ID = ?"
);
@NAMED-QUERY(name="SELECT-CRAWL-STATUS", 
    sql="SELECT ID FROM CRAWL WHERE URL_BASE = ? AND STATUS = ? "
);