CREATE TABLE CRAWL (ID VARCHAR(8) PRIMARY KEY, STATUS VARCHAR(6), URL_BASE VARCHAR(1000));
CREATE TABLE CRAWL_URL (ID INT PRIMARY KEY AUTO_INCREMENT, URL VARCHAR(1000) NOT NULL, CRAWL_ID VARCHAR(8), FOREIGN KEY (CRAWL_ID) REFERENCES CRAWL(ID) );

